### ISSUE TITLE
RFE: Support Go 1.5 flag 'nicer usage message' style usage messages

### ISSUE THREAD

**Issue by siebenmann** [spf13/pflag#55]
The standard Go flag package was changed to have significantly nicer and more Unix-style flag usage messages in commit golang/go@51d66601c45572484ed20f3a2be6f67d648b5f22 (with some subsequent refinements). It would be nice if pflag could be updated to this style as well to match flag.

(If this is of interest, I can take a shot at porting the changes from the flag package to pflag and submitting them as a pull request.)

**Comment by rasky** [comment]
I'd love that. In fact, just not showing defaults when it's the zero-construction for the type would be a good improvement. Things like "--verbose[=0]" for counters or "--interactive[=true]" for booleans are really weird to see.

**Comment by eparis** [comment]
I actually kinda dislike the new style but won't block such work if other like it. I will point out that since more of our flags take optional arguments (bools and counters, whereas upstream is only bools) we have more reason to show 0 vales as the `[]` is really the only way to show the 'optional-ness' of a flag...

(needless nit, booleans 0 value is false, so your true example should show up...)
